export declare const userRoleEnum: import("drizzle-orm/pg-core").PgEnum<["player", "coach", "club_staff", "admin"]>;
export declare const userSkillLevelEnum: import("drizzle-orm/pg-core").PgEnum<["beginner", "intermediate", "advanced", "professional"]>;
export declare const genderEnum: import("drizzle-orm/pg-core").PgEnum<["male", "female", "other", "unknown"]>;
export declare const notificationChannelEnum: import("drizzle-orm/pg-core").PgEnum<["whatsapp", "telegram", "email", "app_push"]>;
export declare const courtTypeEnum: import("drizzle-orm/pg-core").PgEnum<["paddle", "tennis"]>;
export declare const bookingStatusEnum: import("drizzle-orm/pg-core").PgEnum<["confirmed", "pending_payment", "cancelled", "completed"]>;
export declare const paymentStatusEnum: import("drizzle-orm/pg-core").PgEnum<["success", "failed", "pending", "refunded", "partial"]>;
export declare const paymentMethodEnum: import("drizzle-orm/pg-core").PgEnum<["card", "cash", "bank_transfer", "bonus_points"]>;
export declare const bookingPurposeEnum: import("drizzle-orm/pg-core").PgEnum<["free_play", "group_training", "private_training", "tournament_match", "other"]>;
export declare const classParticipantStatusEnum: import("drizzle-orm/pg-core").PgEnum<["registered", "attended", "no_show", "cancelled"]>;
export declare const classTypeEnum: import("drizzle-orm/pg-core").PgEnum<["group_training", "open_play_session", "coached_drill"]>;
export declare const classScheduleStatusEnum: import("drizzle-orm/pg-core").PgEnum<["scheduled", "cancelled", "completed", "draft"]>;
export declare const trainingPackageTypeEnum: import("drizzle-orm/pg-core").PgEnum<["group_training", "private_training"]>;
export declare const userTrainingPackageStatusEnum: import("drizzle-orm/pg-core").PgEnum<["active", "expired", "completed", "cancelled"]>;
export declare const gameSessionStatusEnum: import("drizzle-orm/pg-core").PgEnum<["open_for_players", "full", "in_progress", "completed", "cancelled"]>;
export declare const gameTypeEnum: import("drizzle-orm/pg-core").PgEnum<["public_match", "private_match"]>;
export declare const ratingChangeReasonEnum: import("drizzle-orm/pg-core").PgEnum<["game_session", "tournament_match", "manual_adjustment"]>;
export declare const tournamentTypeEnum: import("drizzle-orm/pg-core").PgEnum<["singles_elimination", "doubles_round_robin", "other"]>;
export declare const tournamentStatusEnum: import("drizzle-orm/pg-core").PgEnum<["upcoming", "registration_open", "in_progress", "completed", "cancelled"]>;
export declare const tournamentParticipantStatusEnum: import("drizzle-orm/pg-core").PgEnum<["registered", "checked_in", "withdrawn"]>;
