version: '3.8'
services:
  bot:
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file:
      - .env
    command: bun run scripts/run-bot.ts

volumes:
  node_modules:
